// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: cache/proto/cache.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_cache_proto_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SearchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	IsHit         bool                   `protobuf:"varint,2,opt,name=isHit,proto3" json:"isHit,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_cache_proto_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_cache_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SearchResponse) GetIsHit() bool {
	if x != nil {
		return x.IsHit
	}
	return false
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CacheTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPrompt    string                 `protobuf:"bytes,1,opt,name=userPrompt,proto3" json:"userPrompt,omitempty"`
	AiResponse    string                 `protobuf:"bytes,2,opt,name=aiResponse,proto3" json:"aiResponse,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=modelName,proto3" json:"modelName,omitempty"`
	TokenUsage    int32                  `protobuf:"varint,4,opt,name=tokenUsage,proto3" json:"tokenUsage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheTaskRequest) Reset() {
	*x = CacheTaskRequest{}
	mi := &file_cache_proto_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheTaskRequest) ProtoMessage() {}

func (x *CacheTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheTaskRequest.ProtoReflect.Descriptor instead.
func (*CacheTaskRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_cache_proto_rawDescGZIP(), []int{2}
}

func (x *CacheTaskRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *CacheTaskRequest) GetAiResponse() string {
	if x != nil {
		return x.AiResponse
	}
	return ""
}

func (x *CacheTaskRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CacheTaskRequest) GetTokenUsage() int32 {
	if x != nil {
		return x.TokenUsage
	}
	return 0
}

type SaveCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCacheResponse) Reset() {
	*x = SaveCacheResponse{}
	mi := &file_cache_proto_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCacheResponse) ProtoMessage() {}

func (x *SaveCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCacheResponse.ProtoReflect.Descriptor instead.
func (*SaveCacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SaveCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cache_proto_cache_proto protoreflect.FileDescriptor

const file_cache_proto_cache_proto_rawDesc = "" +
	"\n" +
	"\x17cache/proto/cache.proto\x12\x05cache\"=\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"T\n" +
	"\x0eSearchResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x14\n" +
	"\x05isHit\x18\x02 \x01(\bR\x05isHit\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x90\x01\n" +
	"\x10CacheTaskRequest\x12\x1e\n" +
	"\n" +
	"userPrompt\x18\x01 \x01(\tR\n" +
	"userPrompt\x12\x1e\n" +
	"\n" +
	"aiResponse\x18\x02 \x01(\tR\n" +
	"aiResponse\x12\x1c\n" +
	"\tmodelName\x18\x03 \x01(\tR\tmodelName\x12\x1e\n" +
	"\n" +
	"tokenUsage\x18\x04 \x01(\x05R\n" +
	"tokenUsage\")\n" +
	"\x11SaveCacheResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x8c\x01\n" +
	"\fCacheService\x12<\n" +
	"\rSearchSimilar\x12\x14.cache.SearchRequest\x1a\x15.cache.SearchResponse\x12>\n" +
	"\tSaveCache\x12\x17.cache.CacheTaskRequest\x1a\x18.cache.SaveCacheResponseB\rZ\vcache/protob\x06proto3"

var (
	file_cache_proto_cache_proto_rawDescOnce sync.Once
	file_cache_proto_cache_proto_rawDescData []byte
)

func file_cache_proto_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_cache_proto_rawDesc), len(file_cache_proto_cache_proto_rawDesc)))
	})
	return file_cache_proto_cache_proto_rawDescData
}

var file_cache_proto_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cache_proto_cache_proto_goTypes = []any{
	(*SearchRequest)(nil),     // 0: cache.SearchRequest
	(*SearchResponse)(nil),    // 1: cache.SearchResponse
	(*CacheTaskRequest)(nil),  // 2: cache.CacheTaskRequest
	(*SaveCacheResponse)(nil), // 3: cache.SaveCacheResponse
}
var file_cache_proto_cache_proto_depIdxs = []int32{
	0, // 0: cache.CacheService.SearchSimilar:input_type -> cache.SearchRequest
	2, // 1: cache.CacheService.SaveCache:input_type -> cache.CacheTaskRequest
	1, // 2: cache.CacheService.SearchSimilar:output_type -> cache.SearchResponse
	3, // 3: cache.CacheService.SaveCache:output_type -> cache.SaveCacheResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_proto_cache_proto_init() }
func file_cache_proto_cache_proto_init() {
	if File_cache_proto_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_cache_proto_rawDesc), len(file_cache_proto_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_cache_proto_msgTypes,
	}.Build()
	File_cache_proto_cache_proto = out.File
	file_cache_proto_cache_proto_goTypes = nil
	file_cache_proto_cache_proto_depIdxs = nil
}
