// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: rag/proto/rag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,6,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,7,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_rag_proto_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Chunk) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Chunk) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Chunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Chunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_rag_proto_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngestedCount int32                  `protobuf:"varint,1,opt,name=ingested_count,json=ingestedCount,proto3" json:"ingested_count,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_rag_proto_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetIngestedCount() int32 {
	if x != nil {
		return x.IngestedCount
	}
	return 0
}

func (x *IngestResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Threshold     float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_rag_proto_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type RetrievedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedChunk) Reset() {
	*x = RetrievedChunk{}
	mi := &file_rag_proto_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedChunk) ProtoMessage() {}

func (x *RetrievedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedChunk.ProtoReflect.Descriptor instead.
func (*RetrievedChunk) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievedChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *RetrievedChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievedChunk) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RetrievedChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*RetrievedChunk      `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_rag_proto_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveResponse) GetChunks() []*RetrievedChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *RetrieveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocRequest) Reset() {
	*x = DeleteDocRequest{}
	mi := &file_rag_proto_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocRequest) ProtoMessage() {}

func (x *DeleteDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rag_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DeleteDocRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

var File_rag_proto_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rag_proto_rawDesc = "" +
	"\n" +
	"\x13rag/proto/rag.proto\x12\x03rag\x1a\x1bgoogle/protobuf/empty.proto\"\xcf\x01\n" +
	"\x05Chunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1f\n" +
	"\vchunk_index\x18\x06 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\a \x01(\x05R\vtotalChunks\"3\n" +
	"\rIngestRequest\x12\"\n" +
	"\x06chunks\x18\x01 \x03(\v2\n" +
	".rag.ChunkR\x06chunks\"d\n" +
	"\x0eIngestResponse\x12%\n" +
	"\x0eingested_count\x18\x01 \x01(\x05R\ringestedCount\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"z\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\"s\n" +
	"\x0eRetrievedChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\"U\n" +
	"\x10RetrieveResponse\x12+\n" +
	"\x06chunks\x18\x01 \x03(\v2\x13.rag.RetrievedChunkR\x06chunks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x10DeleteDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection2\xb4\x01\n" +
	"\n" +
	"RagService\x121\n" +
	"\x06Ingest\x12\x12.rag.IngestRequest\x1a\x13.rag.IngestResponse\x127\n" +
	"\bRetrieve\x12\x14.rag.RetrieveRequest\x1a\x15.rag.RetrieveResponse\x12:\n" +
	"\tDeleteDoc\x12\x15.rag.DeleteDocRequest\x1a\x16.google.protobuf.EmptyB\vZ\trag/protob\x06proto3"

var (
	file_rag_proto_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rag_proto_rawDescData []byte
)

func file_rag_proto_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rag_proto_rawDesc), len(file_rag_proto_rag_proto_rawDesc)))
	})
	return file_rag_proto_rag_proto_rawDescData
}

var file_rag_proto_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rag_proto_rag_proto_goTypes = []any{
	(*Chunk)(nil),            // 0: rag.Chunk
	(*IngestRequest)(nil),    // 1: rag.IngestRequest
	(*IngestResponse)(nil),   // 2: rag.IngestResponse
	(*RetrieveRequest)(nil),  // 3: rag.RetrieveRequest
	(*RetrievedChunk)(nil),   // 4: rag.RetrievedChunk
	(*RetrieveResponse)(nil), // 5: rag.RetrieveResponse
	(*DeleteDocRequest)(nil), // 6: rag.DeleteDocRequest
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_rag_proto_rag_proto_depIdxs = []int32{
	0, // 0: rag.IngestRequest.chunks:type_name -> rag.Chunk
	4, // 1: rag.RetrieveResponse.chunks:type_name -> rag.RetrievedChunk
	1, // 2: rag.RagService.Ingest:input_type -> rag.IngestRequest
	3, // 3: rag.RagService.Retrieve:input_type -> rag.RetrieveRequest
	6, // 4: rag.RagService.DeleteDoc:input_type -> rag.DeleteDocRequest
	2, // 5: rag.RagService.Ingest:output_type -> rag.IngestResponse
	5, // 6: rag.RagService.Retrieve:output_type -> rag.RetrieveResponse
	7, // 7: rag.RagService.DeleteDoc:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rag_proto_rag_proto_init() }
func file_rag_proto_rag_proto_init() {
	if File_rag_proto_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rag_proto_rawDesc), len(file_rag_proto_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_rag_proto_msgTypes,
	}.Build()
	File_rag_proto_rag_proto = out.File
	file_rag_proto_rag_proto_goTypes = nil
	file_rag_proto_rag_proto_depIdxs = nil
}
