FROM golang:1.25.7-alpine3.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd/
COPY cache ./cache/
COPY embedding ./embedding/
COPY completion ./completion/

RUN CGO_ENABLED=0 GOOS=linux go build -o /embedding-bin ./cmd/embedding

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /embedding-bin .

EXPOSE 50051

CMD [ "./embedding-bin" ]