// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: completion/proto/completion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stream        bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_completion_proto_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_completion_proto_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_completion_proto_completion_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CompletionRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type CompletionChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	TokenUsage    int32                  `protobuf:"varint,4,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChunk) Reset() {
	*x = CompletionChunk{}
	mi := &file_completion_proto_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChunk) ProtoMessage() {}

func (x *CompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_completion_proto_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChunk.ProtoReflect.Descriptor instead.
func (*CompletionChunk) Descriptor() ([]byte, []int) {
	return file_completion_proto_completion_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompletionChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CompletionChunk) GetTokenUsage() int32 {
	if x != nil {
		return x.TokenUsage
	}
	return 0
}

var File_completion_proto_completion_proto protoreflect.FileDescriptor

const file_completion_proto_completion_proto_rawDesc = "" +
	"\n" +
	"!completion/proto/completion.proto\x12\n" +
	"completion\"\x9e\x01\n" +
	"\x11CompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\"v\n" +
	"\x0fCompletionChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1f\n" +
	"\vtoken_usage\x18\x04 \x01(\x05R\n" +
	"tokenUsage2^\n" +
	"\x11CompletionService\x12I\n" +
	"\tGetStream\x12\x1d.completion.CompletionRequest\x1a\x1b.completion.CompletionChunk0\x01B\x12Z\x10completion/protob\x06proto3"

var (
	file_completion_proto_completion_proto_rawDescOnce sync.Once
	file_completion_proto_completion_proto_rawDescData []byte
)

func file_completion_proto_completion_proto_rawDescGZIP() []byte {
	file_completion_proto_completion_proto_rawDescOnce.Do(func() {
		file_completion_proto_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_completion_proto_completion_proto_rawDesc), len(file_completion_proto_completion_proto_rawDesc)))
	})
	return file_completion_proto_completion_proto_rawDescData
}

var file_completion_proto_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_completion_proto_completion_proto_goTypes = []any{
	(*CompletionRequest)(nil), // 0: completion.CompletionRequest
	(*CompletionChunk)(nil),   // 1: completion.CompletionChunk
}
var file_completion_proto_completion_proto_depIdxs = []int32{
	0, // 0: completion.CompletionService.GetStream:input_type -> completion.CompletionRequest
	1, // 1: completion.CompletionService.GetStream:output_type -> completion.CompletionChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_completion_proto_completion_proto_init() }
func file_completion_proto_completion_proto_init() {
	if File_completion_proto_completion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_completion_proto_completion_proto_rawDesc), len(file_completion_proto_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_completion_proto_completion_proto_goTypes,
		DependencyIndexes: file_completion_proto_completion_proto_depIdxs,
		MessageInfos:      file_completion_proto_completion_proto_msgTypes,
	}.Build()
	File_completion_proto_completion_proto = out.File
	file_completion_proto_completion_proto_goTypes = nil
	file_completion_proto_completion_proto_depIdxs = nil
}
